# Generated by Django 2.1.2 on 2019-06-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
        migrations.DeleteModel(
            name='SomeModel2',
        ),
    ]
