# Generated by Django 2.1.2 on 2019-06-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20190608_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('transport_id', models.IntegerField()),
                ('start_time', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('is_validated', models.IntegerField()),
                ('balance', models.FloatField()),
                ('fid_card', models.IntegerField()),
                ('register_date', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('session_id', models.IntegerField()),
                ('value', models.FloatField()),
                ('time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.IntegerField()),
            ],
        ),
    ]
