# Generated by Django 2.1.2 on 2019-06-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_driver_drivesession_passenger_trace_transaction_transport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriveSession',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Trace',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
