# Generated by Django 2.1.2 on 2019-06-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190608_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivesession',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='drivesession',
            name='tr_id',
        ),
        migrations.DeleteModel(
            name='Trace',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='session_id',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriveSession',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
