# Generated by Django 2.1.2 on 2019-06-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20190608_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DriveSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField()),
                ('is_continues', models.BooleanField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_validated', models.BooleanField()),
                ('balance', models.FloatField()),
                ('fid_card', models.IntegerField()),
                ('register_date', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('trace_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('time', models.PositiveIntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Passenger')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DriveSession')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='transportType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TransportType'),
        ),
        migrations.AddField(
            model_name='drivesession',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transport'),
        ),
    ]
