# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: other_models.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core.proto_models.db_models_pb2 as db__models__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='other_models.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12other_models.proto\x1a\x0f\x64\x62_models.proto\"{\n\x14\x43lientValidationList\x12\x33\n\x07\x43lients\x18\x01 \x03(\x0b\x32\".ClientValidationList.ClientsEntry\x1a.\n\x0c\x43lientsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"2\n\x07Payment\x12\x10\n\x08\x43lientID\x18\x01 \x01(\x03\x12\x15\n\rTransactionID\x18\x02 \x01(\x03\"\x81\x01\n\x10\x43ompletedPayment\x12\r\n\x05price\x18\x01 \x01(\t\x12\x1c\n\x04type\x18\x02 \x01(\x0e\x32\x0e.TransportType\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\x05\x12\n\n\x02id\x18\x05 \x01(\x03\x12\x17\n\x06status\x18\x06 \x01(\x0e\x32\x07.Status\"=\n\x16RecentPaymentsResponce\x12#\n\x08Payments\x18\x01 \x03(\x0b\x32\x11.CompletedPaymentb\x06proto3')
  ,
  dependencies=[db__models__pb2.DESCRIPTOR,])




_CLIENTVALIDATIONLIST_CLIENTSENTRY = _descriptor.Descriptor(
  name='ClientsEntry',
  full_name='ClientValidationList.ClientsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ClientValidationList.ClientsEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ClientValidationList.ClientsEntry.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=162,
)

_CLIENTVALIDATIONLIST = _descriptor.Descriptor(
  name='ClientValidationList',
  full_name='ClientValidationList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Clients', full_name='ClientValidationList.Clients', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CLIENTVALIDATIONLIST_CLIENTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=162,
)


_PAYMENT = _descriptor.Descriptor(
  name='Payment',
  full_name='Payment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ClientID', full_name='Payment.ClientID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TransactionID', full_name='Payment.TransactionID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=214,
)


_COMPLETEDPAYMENT = _descriptor.Descriptor(
  name='CompletedPayment',
  full_name='CompletedPayment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='CompletedPayment.price', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='CompletedPayment.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='CompletedPayment.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='CompletedPayment.date', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='CompletedPayment.id', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='CompletedPayment.status', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=346,
)


_RECENTPAYMENTSRESPONCE = _descriptor.Descriptor(
  name='RecentPaymentsResponce',
  full_name='RecentPaymentsResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Payments', full_name='RecentPaymentsResponce.Payments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=409,
)

_CLIENTVALIDATIONLIST_CLIENTSENTRY.containing_type = _CLIENTVALIDATIONLIST
_CLIENTVALIDATIONLIST.fields_by_name['Clients'].message_type = _CLIENTVALIDATIONLIST_CLIENTSENTRY
_COMPLETEDPAYMENT.fields_by_name['type'].enum_type = db__models__pb2._TRANSPORTTYPE
_COMPLETEDPAYMENT.fields_by_name['status'].enum_type = db__models__pb2._STATUS
_RECENTPAYMENTSRESPONCE.fields_by_name['Payments'].message_type = _COMPLETEDPAYMENT
DESCRIPTOR.message_types_by_name['ClientValidationList'] = _CLIENTVALIDATIONLIST
DESCRIPTOR.message_types_by_name['Payment'] = _PAYMENT
DESCRIPTOR.message_types_by_name['CompletedPayment'] = _COMPLETEDPAYMENT
DESCRIPTOR.message_types_by_name['RecentPaymentsResponce'] = _RECENTPAYMENTSRESPONCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientValidationList = _reflection.GeneratedProtocolMessageType('ClientValidationList', (_message.Message,), {

  'ClientsEntry' : _reflection.GeneratedProtocolMessageType('ClientsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLIENTVALIDATIONLIST_CLIENTSENTRY,
    '__module__' : 'other_models_pb2'
    # @@protoc_insertion_point(class_scope:ClientValidationList.ClientsEntry)
    })
  ,
  'DESCRIPTOR' : _CLIENTVALIDATIONLIST,
  '__module__' : 'other_models_pb2'
  # @@protoc_insertion_point(class_scope:ClientValidationList)
  })
_sym_db.RegisterMessage(ClientValidationList)
_sym_db.RegisterMessage(ClientValidationList.ClientsEntry)

Payment = _reflection.GeneratedProtocolMessageType('Payment', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENT,
  '__module__' : 'other_models_pb2'
  # @@protoc_insertion_point(class_scope:Payment)
  })
_sym_db.RegisterMessage(Payment)

CompletedPayment = _reflection.GeneratedProtocolMessageType('CompletedPayment', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETEDPAYMENT,
  '__module__' : 'other_models_pb2'
  # @@protoc_insertion_point(class_scope:CompletedPayment)
  })
_sym_db.RegisterMessage(CompletedPayment)

RecentPaymentsResponce = _reflection.GeneratedProtocolMessageType('RecentPaymentsResponce', (_message.Message,), {
  'DESCRIPTOR' : _RECENTPAYMENTSRESPONCE,
  '__module__' : 'other_models_pb2'
  # @@protoc_insertion_point(class_scope:RecentPaymentsResponce)
  })
_sym_db.RegisterMessage(RecentPaymentsResponce)


_CLIENTVALIDATIONLIST_CLIENTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
